server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: fetch-user
          uri: lb://FETCH-USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: user-convert
          uri: lb://USER-CONVERTER-SERVICE
          predicates:
            - Path=/api/transformUsers**